require("./indexB.html");
// require("./css/materialdesignicons.css");
// require("./css/video-js.min.css");
require("./node_modules/video.js/dist/video-js.css");
require("./css/master.css");
// require("./js/video.min.js");
// require("./js/videojs-contrib-hls.min");
require("./js/master.js");
import * as OfflinePluginRuntime from "offline-plugin/runtime";
OfflinePluginRuntime.install();
